#!/usr/bin/perl

use strict;
use warnings;
use Util::IPC::MB;
use Text::SimpleTable;

my $mb = Util::IPC::MB->new();
my $slab = $mb->{slab};

&report;

###############################################
#  slab summary report
###############################################
sub report {

  my $table = Text::SimpleTable->new(
    [2,  'id'     ],
    [4,  'num'    ],
    [4,  'size'   ],
    [4,  'used'   ],
    [4,  'last'   ],
    [9,  'sem_id' ],
    [9,  'shm_id' ],
    [64, 'map'    ],
  );

  for (my $i = 0; $i < @$slab; ++$i) {
    my $s = $slab->[$i];
    my $map = join "\n", @{slab_map($s)};
    $table->row(
      $i, 
      $s->cnt(),
      $s->size(),
      $s->used(),
      $s->last(),
      $s->{sem}->id(),
      ${$s->{shm}},
      $map
    );
    $table->hr if $i < @$slab - 1;
  }

  print $table->draw;
}

###############################################
#  slab map information
###############################################
sub slab_map {
  my $slab = shift;
  my @map;
  my @seg_64;
  for (my $i = 0; $i < $slab->cnt(); ++$i) {
    if ( $slab->map($i) ){
      push @seg_64, 1; 
    } 
    else {
      push @seg_64, 0;
    }
    if ( ($i+1)%64 == 0 ) {
      push @map, join '', @seg_64;
      @seg_64 = ();
    }
  }  
  return \@map;
}
  
  
