#!/usr/bin/perl

use strict;
use warnings;
use Util::Run;
use Env qw/$APP_HOME $PERL5LIB/;
use Util::Upgrade::Client;
use POE;
use POSIX qw/pause/;

##########################################
#  kernel preparation
##########################################
my $kernel = Util::Run->launch(
  mode      => "process_tree",
  pidfile   => "$APP_HOME/log/ucli.pid",         # logger, loggerd need pidfile
  logname   => "logd",
  logurl    => "file://$APP_HOME/log/Zucli.log",  #
  loglevel  => 'DEBUG',
  name      => 'Zucli',
);

Data::Dump->dump($kernel);

my %modules = (
  Zupgrade  => {
    code => \&upgrade,
    para => {},
    size => 1,
    reap => 1,
  },

  Zworker => {
    code => \&worker,
    para => {},
    size => 2,
    reap => 1,
  }
);

##########################################
# run modules in the kernel
##########################################
$kernel->run(
  module  => \%modules,
  main    => sub { while(1) { pause(); } },
  args    => [],  
);

sub upgrade {
  unless( Util::Upgrade::Client->spawn(
    remoteaddr     => '127.0.0.1',
    remoteport     => 5454,
    chk_interval   => 10,
    fail_interval  => 10,
    maxfail        => 10,
    app_home       => "$PERL5LIB/Util/Upgrade/client",
    upgrade_home   => "$PERL5LIB/Util/Upgrade/client/version",
  )) {
    exit 0;
  }
  $poe_kernel->run();
}

sub worker {
  my $logger = $run_kernel->{logger}->clone("$0.log");
  my $i = 0;
  while(1) {
    $logger->debug("I am busy $i");
    $i++;
    sleep 2;
  }
}


