#!/usr/bin/env perl
use Mojolicious::Lite;

# Documentation browser under "/perldoc"
plugin 'PODRenderer';

get '/' => sub {
  my $self = shift;
  $self->render('hello');
};

app->start;
__DATA__

@@ hello.html.ep
% layout 'defau';
% title 'Welcome';
<p><font color="red">Welcome to the Mojolicious real-time web framework!</font></p>
<p>Thank you very much!</p>
@@ layouts/defau.html.ep
<!DOCTYPE html>
<html>
  <head><title><%= title %></title></head>
  <body><%= content %></body>
</html>
